services:
    store:
        image: postgres:17.5-alpine3.22
        environment:
            - POSTGRES_PASSWORD=${STORE_PASSWORD}
            - POSTGRES_USER=${STORE_USER}
            - POSTGRES_DB=${STORE_DB}
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    cache:
        image: memcached:1.6.38-alpine
        ports:
            - 11211:11211
volumes:
    pg-data:
