services:
    store:
        image: postgres:17.5-alpine3.22
        environment:
            - POSTGRES_PASSWORD=${STORE_PASSWORD}
            - POSTGRES_USER=${STORE_USER}
            - POSTGRES_DB=${STORE_DB}
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - go-web

    cache:
        image: memcached:1.6.38-alpine
        networks:
            - go-web

    backend:
        image: ghcr.io/livensmi1e/go-web:latest
        networks:
            - go-web
        depends_on:
            - store
        env_file:
            - .env.prod

volumes:
    pg-data:

networks:
    go-web:
        driver: bridge
